log_format ohd_tsv '$time_iso8601\t$remote_addr\t$request_method\t$host\t$uri\t$status\t$request_time\t$http_traceparent\t$args\t$server_protocol\t$body_bytes_sent\t$http_referer\t$http_user_agent\t$http_tracestate';
access_log /var/log/nginx/ohd-access.log ohd_tsv;
